// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZfBM1b3AH4E-XrtLUw01XQ4m130eS3-Y',
    appId: '1:19997583713:web:624c34c6409d9b35dc3d20',
    messagingSenderId: '19997583713',
    projectId: 'trackify-77e1a',
    authDomain: 'trackify-77e1a.firebaseapp.com',
    storageBucket: 'trackify-77e1a.firebasestorage.app',
    measurementId: 'G-3KT6NGYF0B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZfBM1b3AH4E-XrtLUw01XQ4m130eS3-Y',
    appId: '1:19997583713:android:624c34c6409d9b35dc3d20',
    messagingSenderId: '19997583713',
    projectId: 'trackify-77e1a',
    storageBucket: 'trackify-77e1a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZfBM1b3AH4E-XrtLUw01XQ4m130eS3-Y',
    appId: '1:19997583713:ios:624c34c6409d9b35dc3d20',
    messagingSenderId: '19997583713',
    projectId: 'trackify-77e1a',
    storageBucket: 'trackify-77e1a.firebasestorage.app',
    iosBundleId: 'com.example.trackify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZfBM1b3AH4E-XrtLUw01XQ4m130eS3-Y',
    appId: '1:19997583713:ios:624c34c6409d9b35dc3d20',
    messagingSenderId: '19997583713',
    projectId: 'trackify-77e1a',
    storageBucket: 'trackify-77e1a.firebasestorage.app',
    iosBundleId: 'com.example.trackify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZfBM1b3AH4E-XrtLUw01XQ4m130eS3-Y',
    appId: '1:19997583713:web:624c34c6409d9b35dc3d20',
    messagingSenderId: '19997583713',
    projectId: 'trackify-77e1a',
    authDomain: 'trackify-77e1a.firebaseapp.com',
    storageBucket: 'trackify-77e1a.firebasestorage.app',
    measurementId: 'G-3KT6NGYF0B',
  );
}
